src/ComicMoviesGallery/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicMoviesGallery.Models
{
    public class Artist
    {
        public string Name { get; set; }
        public string Role { get; set; }
    }
}

src/ComicMoviesGallery/Models/ComicMovie.cs

﻿using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicMoviesGallery.Models
{
    public class ComicMovie
    {
        public int Id { get; set; }
        public string MovieTitle { get; set; }
        public string DescriptionHtml { get; set; }
        public Artist[] Artists { get; set; }

        public string DisplayText
        {
            get
            {
                return MovieTitle;
            }
        }

        // series-title-issuenumber.jpg
        public string CoverImageFileName
        {
            get
            {
                return MovieTitle.Replace(" ", "-")
                    .ToLower() + ".jpg";
            }
        }
    }
}

src/ComicMoviesGallery/Controllers/ComicMoviesController.cs
using ComicMoviesGallery.Data;
using ComicMoviesGallery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComicMoviesGallery.Controllers
{
    public class ComicMoviesController : Controller
    {
        private ComicMovieRepository _comicMovieRepository = null;

        public ComicMoviesController()
        {
            _comicMovieRepository = new ComicMovieRepository();
        }

        public ActionResult Index()
        {
            var comicMovie = _comicMovieRepository.GetComicMovies();

            return View(comicMovie);
        }

        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var comicMovie = _comicMovieRepository.GetComicMovie((int)id);

            return View(comicMovie);
        }
    }
}

src/ComicMoviesGallery/Views/ComicMovies/Detail.cshtml
@model ComicMoviesGallery.Models.ComicMovie

@{
    ViewBag.Title = Model.DisplayText;
    ViewBag.ShowBackBar = true;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.DisplayText</h2>

<div class="row">
    <div class="col-md-6">
        <div class="well">
            <h5><label>Series Title:</label> @Model.MovieTitle</h5>

            
            @if (Model.Artists.Length > 0)
            {
                <h5>Artists:</h5>
                <div>
                    <ul>
                        @foreach (var artist in Model.Artists)
                        {
                            <li>@artist.Role: @artist.Name</li>
                        }
                    </ul>
                </div>
            }
        </div>
        <h5>Description:</h5>
        <div>@Html.Raw(Model.DescriptionHtml)</div>
    </div>
    <div class="col-md-6">
        <img src="/Images/@Model.CoverImageFileName"
             alt="@Model.DisplayText" class="img-responsive" />
    </div>
</div>

src/ComicMoviesGallery/Views/ComicMovies/Index.cshtml


@model ComicMoviesGallery.Models.ComicMovie[]

@{
    ViewBag.Title = "Comic Movies";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    @foreach (var comicMovie in Model)
    {
        <div class="col-md-3">
            <h4>
                @Html.ActionLink(comicMovie.DisplayText, "Detail",
               new { id = comicMovie.Id })
            </h4>
            <a href="@Url.Action("Detail", new { id = comicMovie.Id })">
                <img src="/Images/@comicMovie.CoverImageFileName"
                     alt="@comicMovie.DisplayText"
                     class="img-responsive" />
            </a>
        </div>
    }
</div>





src/ComicMoviesGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Comic Movie Gallery</title>
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Comic Movie Gallery", "Index", "ComicMovies", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- Add menu items here -->
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Comic Movie Gallery</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>